apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: ticketing

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:

      serviceAccountName: frontend-sa

      containers:
        - name: frontend
          image: toni680/ticketing-frontend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          
          env:
            - name: FRONTEND_PORT
              value: "3000"

            - name: API_BASE_URL
              value: "/api"