apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: ticketing
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: ticketing
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: ticketing
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: ticketing
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: ticketing
automountServiceAccountToken: false