name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install API dependencies
        working-directory: ./api
        run: npm install

      - name: Install Worker dependencies
        working-directory: ./worker
        run: npm install

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build API image
        run: docker build -t ticketing-api ./api

      - name: Build Worker image
        run: docker build -t ticketing-worker ./worker

      - name: Build Frontend image
        run: docker build -t ticketing-frontend ./frontend